geekshop/adminapp/urls.py
from django.urls import path

from adminapp.views import UserListView, UserCreateView, UserUpdateView, UserDeleteView, IndexTemplateView, \
    AdminCategoryView, AdminCategoryUpdateView, AdminCategoryDeleteView, AdminCategoryCreateView, AdminProductsShowView, \
    AdminProductCreateView, AdminProductChangeView, AdminProductDeleteView

app_name = 'adminapp'
urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('users/', UserListView.as_view(), name='admin_users'),
    path('user-create/', UserCreateView.as_view(), name='admin_user_create'),
    path('user-update/<int:pk>/', UserUpdateView.as_view(), name='admin_user_update'),
    path('user-delete/<int:pk>/', UserDeleteView.as_view(), name='admin_user_delete'),
    path('categories/', AdminCategoryView.as_view(), name='admin_category'),
    path('category_update/<int:pk>/', AdminCategoryUpdateView.as_view(), name='category_update'),
    path('category_delete/<int:pk>/', AdminCategoryDeleteView.as_view(), name='category_delete'),
    path('category_create/', AdminCategoryCreateView.as_view(), name='category_create'),
    path('admin_products/', AdminProductsShowView.as_view(), name='admin_products'),
    path('admin_product_create/', AdminProductCreateView.as_view(), name='admin_product_create'),
    path('admin_product_update/<int:pk>/', AdminProductChangeView.as_view(), name='admin_product_update'),
    path('admin_product_delete/<int:pk>/', AdminProductDeleteView.as_view(), name='admin_product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path
from authapp.views import LoginGBView, RegisterView, Logout, ProfileFormView

app_name = 'authapp'

urlpatterns = [
    path('login/', LoginGBView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('profile/', ProfileFormView.as_view(), name='profile'),

    path('verify/<str:email>/<str:activate_key>/', RegisterView.verify, name='verify')
]

geekshop/basket/urls.py
from django.urls import path

from basket.views import basket_add, basket_remove, basket_edit

app_name = 'basket'

urlpatterns = [
    path('add/<int:id>/', basket_add, name='basket_add'),
    path('remove/<int:basket_id>', basket_remove, name='basket_remove'),
    path('edit/<int:basket_id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('adminapp/', include('adminapp.urls', namespace='adminapp')),
    path('ordersapp/', include('ordersapp.urls', namespace='orders')),
    path("", include("social_django.urls", namespace="social")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.forms import ModelForm

from authapp.models import User
from mainapp.models import ProductCategories, Product


class UserAdminRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'last_name', 'first_name', 'email', 'image', 'age')

    def __init__(self, *args, **kwargs):
        super(UserAdminRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['password1'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['password2'].widget.attrs['placeholder'] = 'Повторите пароль'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Ведите фамилию'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Введите имя'
        self.fields['email'].widget.attrs['placeholder'] = 'Введите email'
        self.fields['image'].widget.attrs['placeholder'] = 'Добавить фотографию'
        self.fields['age'].widget.attrs['placeholder'] = 'Возраст'

        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'


class UserAdminProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'last_name', 'first_name', 'email', 'image', 'age')

    def __init__(self, *args, **kwargs):
        super(UserAdminProfileForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['readonly'] = True

        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'


class AdminCategoryChange(ModelForm):
    class Meta:
        model = ProductCategories
        fields = ('name', 'descriptions', 'is_active')

    def __init__(self, *args, **kwargs):
        super(AdminCategoryChange, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'


class AdminProductCreate(ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'image', 'descriptions', 'price', 'quantity', 'category', 'is_active')

    def __init__(self, *args, **kwars):
        super(AdminProductCreate, self).__init__(*args, **kwars)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-2'

        self.fields['image'].widget.attrs['class'] = 'custom_file-input'

geekshop/adminapp/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy

from adminapp.forms import UserAdminRegisterForm, UserAdminProfileForm, AdminCategoryChange, AdminProductCreate
from adminapp.mixin import BaseClassContextMixin, SuperuserDispatchMixin, AuthorisationDispatchMixin
from authapp.models import User
from django.contrib.auth.decorators import user_passes_test
from django.views.generic import ListView, TemplateView, CreateView, DeleteView, UpdateView

from mainapp.models import ProductCategories, Product


class IndexTemplateView(TemplateView, BaseClassContextMixin, SuperuserDispatchMixin):
    template_name = 'adminapp/admin.html'
    title = 'Главня страница'


class UserListView(ListView, BaseClassContextMixin, SuperuserDispatchMixin, AuthorisationDispatchMixin):
    model = User
    template_name = 'adminapp/admin-users-read.html'
    title = 'Админка | Пользователи'
    context_object_name = 'users'


class UserCreateView(CreateView, BaseClassContextMixin, SuperuserDispatchMixin):
    model = User
    template_name = 'adminapp/admin-users-create.html'
    form_class = UserAdminRegisterForm
    title = 'Админка | Регистрация'
    success_url = reverse_lazy('adminapp:admin_users')


class UserUpdateView(UpdateView, BaseClassContextMixin, SuperuserDispatchMixin):
    model = User
    template_name = 'adminapp/admin-users-update-delete.html'
    form_class = UserAdminProfileForm
    title = 'Админка | Обновление пользователя'
    success_url = reverse_lazy('adminapp:admin_users')


class UserDeleteView(DeleteView, SuperuserDispatchMixin):
    model = User
    template_name = 'adminapp/admin-users-update-delete.html'
    form_class = UserAdminProfileForm
    success_url = reverse_lazy('adminapp:admin_users')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class AdminCategoryView(ListView, SuperuserDispatchMixin, BaseClassContextMixin):
    template_name = 'adminapp/admin_category_read.html'
    title = 'GeekShop | Админка'
    model = ProductCategories
    context_object_name = 'categories'
    success_url = reverse_lazy('adminapp:admin_category')


class AdminCategoryUpdateView(UpdateView, SuperuserDispatchMixin, BaseClassContextMixin):
    model = ProductCategories
    template_name = 'adminapp/admin_category_update-delete.html'
    form_class = AdminCategoryChange
    title = 'Обновление категории'
    context_object_name = 'product_cat_select'
    success_url = reverse_lazy('adminapp:admin_category')


class AdminCategoryDeleteView(DeleteView, SuperuserDispatchMixin, BaseClassContextMixin):
    model = ProductCategories
    template_name = 'adminapp/admin_category_update-delete.html'
    success_url = reverse_lazy('adminapp:admin_category')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.success_url)


class AdminCategoryCreateView(CreateView, SuperuserDispatchMixin, BaseClassContextMixin):
    model = ProductCategories
    title = 'Создание категории'
    template_name = 'adminapp/admin_category_create.html'
    form_class = AdminCategoryChange
    success_url = reverse_lazy('adminapp:admin_category')


class AdminProductsShowView(ListView, SuperuserDispatchMixin, BaseClassContextMixin):
    title = 'Товары'
    model = Product
    context_object_name = 'products'
    template_name = 'adminapp/admin_products_show.html'


class AdminProductCreateView(CreateView, SuperuserDispatchMixin, BaseClassContextMixin):
    title = 'Создание товара'
    template_name = 'adminapp/admin_products_create.html'
    form_class = AdminProductCreate
    model = Product


class AdminProductChangeView(UpdateView, SuperuserDispatchMixin, BaseClassContextMixin):
    template_name = 'adminapp/admin_products_update-delete.html'
    title = 'Изменение товара'
    form_class = AdminProductCreate
    model = Product
    context_object_name = 'product_select'
    success_url = reverse_lazy('adminapp:admin_products')


class AdminProductDeleteView(DeleteView, SuperuserDispatchMixin, BaseClassContextMixin):
    model = Product
    success_url = reverse_lazy('adminapp:admin_products')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.success_url)

geekshop/adminapp/templates/adminapp/admin-users-create.html
{% extends 'adminapp/base.html' %}
{% block context %}
    <div class="container-fluid">
        <h1 class="mt-4">Создание пользователя</h1>
        <form action="{% url 'adminapp:admin_user_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                        {{form.first_name}}
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                       {{ form.last_name}}
                    </div>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="col-lg-12">
                    <div class="custom-file">
                        {{form.image}}
                        <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                    {{ form.username }}
                </div>
                <div class="col-lg-4">
                    <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                        почты</label>
                    {{ form.email }}
                </div>
                 <div class="col-lg-2">
                    <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                    {{ form.age }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                   {{ form.password1 }}
                </div>
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.password2.id_for_label }}">Повторите пароль</label>
                    {{ form.password2 }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/admin-users-read.html
{% extends 'adminapp/base.html' %}
{% block context %}
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for user in users %}
                            <tr>
                                <td><a href="{% url 'adminapp:admin_user_update' user.id %}"
                                       style="color: dodgerblue">{{ user.username }}</a></td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.email }}</td>
                                <td class="text-center">
                                    {% if user.is_staff %}
                                        <i class="fas fa-check-circle"></i>
                                    {% else %}
                                        <i class="fas fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if user.is_active %}
                                        <i class="fas fa-check-circle"></i>
                                    {% else %}
                                        <i class="fas fa-times-circle"></i>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:admin_user_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/admin-users-update-delete.html
{% extends 'adminapp/base.html' %}
{% block context %}
    <div class="container-fluid">
        <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
        <div class="card-body">
            <form action="{% url 'adminapp:admin_user_update' user.id %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{ form.image }}
                            <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-4">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                    <div class="col-lg-2">
                        <label class="small mb-1" for="{{ form.age.id_for_label }}">Возратс</label>
                        {{ form.age }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
            <form action="{% url 'adminapp:admin_user_delete' user.id %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/admin.html
{% extends 'adminapp/base.html' %}
{% block context %}
    <div class="container-fluid">
        <h1 class="mt-4">Административная панель</h1>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/admin_category_create.html
{% extends 'adminapp/base.html' %}
{% block context %}
        <div class="container-fluid">
            <h1 class="mt-4">{{ title }}</h1>
            <form action="{% url 'adminapp:category_create' %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.descriptions.id_for_label }}">Описание</label>
                            {{ form.descriptions }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">

                            <label class="small mb-1" for="{{ form.is_active.id_for_label }}">Активный</label>
                        {{ form.is_active }}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>

{% endblock %}

geekshop/adminapp/templates/adminapp/admin_category_read.html
{% extends 'adminapp/base.html' %}
{% block context %}

    <div class="container-fluid">
        <h1 class="mt-4">{{ title }}</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категории
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Категория</th>
                            <th>Описание</th>
                            <th>Активность</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Категория</th>
                            <th>Описание</th>
                            <th>Активность</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for category in categories %}
                            <tr>
                                <td><a href="{% url 'adminapp:category_update' category.id %}"
                                       style="color: dodgerblue">{{ category.name }}</a></td>
                                <td>{{ category.descriptions }}</td>
                                {% if category.is_active %}
                                    <td class="text-center"><i class="fas fa-check"></i></td>
                                {% else %}
                                    <td class="text-center"><i class="fas fa-times-circle"></i></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:category_create' %}">
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </div>
        </div>
    </div>



{% endblock %}

geekshop/adminapp/templates/adminapp/admin_category_update-delete.html
{% extends 'adminapp/base.html' %}
{% block context %}
    <div class="container-fluid">
        <h1 class="mt-4 ml-3">{{ title }}</h1>
        <div class="card-body">
            <form action="{% url 'adminapp:category_update' product_cat_select.id %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-5">
                        <label class="small mb-1" for="{{ form.name.id_for_label }}">Категория</label>
                        {{ form.name }}
                    </div>
                    <div class="col-lg-1">
                        <label class="small mb-1" for="{{ form.is_active.id_for_label }}">Активный</label>
                        {{ form.is_active }}
                    </div>
                </div>

                    <div class="form-row">
                        <div class="col-lg-5">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
            </form>
            <div class="row">
                <div class="col-lg-12" style="margin-top: 10px;">
                    <form action="{% url 'adminapp:category_delete' product_cat_select.id %}" method="post">
                        {% csrf_token %}
                        <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/admin_products_show.html
{% extends 'adminapp/base.html' %}
{% block context %}
            <div class="container-fluid">
                <h1 class="mt-4">{{ title }}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Категории
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Товар</th>
                                    <th>Категория</th>
                                    <th>Активность</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Товар</th>
                                    <th>Категория</th>
                                    <th>Активность</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for product in products %}
                                <tr>
                                    <td><a href="{% url 'adminapp:admin_product_update' product.id %}" style="color: dodgerblue">{{ product.name }}</a></td>
                                    <td>{{ product.category }}</td>
                                    {% if product.is_active %}
                                    <td class="text-center"><i class="fas fa-check"></i></td>
                                    {% else %}
                                    <td class="text-center"><i class="fas fa-times-circle"></i></td>
                                    {% endif %}
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'adminapp:admin_product_create' %}">
                            <button class="btn btn-success">Создать товар</button>
                        </a>
                    </div>
                </div>
            </div>


{% endblock %}

geekshop/adminapp/templates/adminapp/admin_products_update-delete.html
{% extends 'adminapp/base.html' %}
{% block context %}
    <div class="container-fluid">
        <h1 class="mt-4 ml-3">{{ title }}</h1>
        <div class="card-body">
            <form action="{% url 'adminapp:admin_product_update' product_select.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                        {{ form.name }}
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена</label>
                        {{ form.price }}
                    </div>
                </div>
                    <div class="col-lg-2">
                    <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                    {{ form.category }}
                </div>
                <div class="col-lg-2">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество</label>
                        {{ form.quantity }}
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                            <label class="custom-file-label-label" for="{{ form.image.id_for_label }}">Фото</label>
                        {{ form.image }}
                    </div>
                </div>
                <div class="col-lg-1">
                        <label class="small mb-1" for="{{ form.is_active.id_for_label }}">Активный</label>
                        {{ form.is_active }}
                    </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                        {{ form.description }}
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>
            <div class="row">
                <div class="col-lg-12" style="margin-top: 10px;">
                    <form action="{% url 'adminapp:admin_product_delete' product_select.id %}" method="post">
                        {% csrf_token %}
                        <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                    </form>
                </div>
            </div>
    </div>

        </div>
    </div>
{% endblock %}